source 'http://rubygems.org'

gem 'cucumber'
gem 'capybara'
gem 'rspec'
gem 'rake'
gem 'selenium-webdriver'
gem 'pry'
gem 'site_prism', '~> 2.9'
gem 'rspec-rails', '~> 3.0.0'
gem 'utils', '~> 0.9.0'
gem 'faker', '~> 1.6', '>= 1.6.6'
gem 'bundler', '~> 2.2', '>= 2.2.16'
gem 'chromedriver-helper'
gem 'geckodriver-helper', '~> 0.0.3'
gem 'rspec-expectations', '~> 3.10', '>= 3.10.1'
gem 'rspec', '~> 3.10'